### ISSUE TITLE
segfault when finishing an analytic

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#23]
When Running KINC when I import an expression matrix it segfaults. I have traced the segfault to this section of code in the EAbstractAnalytic class of the abstractanalytic.cpp file.

```
void EAbstractAnalytic::finishRun()
{
   // call finish function of analytic
   finish();
```
if I comment out that finish() line then I do not get a segfault.  I don't understand why that would cause a segfault because finish() is not implemented in the analytic that imports the expression matrix, so it's defaulting to the implementation in the abstract class.

**Comment by 4ctrl-alt-del** [comment]
After spending all day attempting to replicate this segfault I have failed. It works flawlessly for me, I recompiled and ran an import expression matrix analytic a million times and it always worked. I am at a loss why that is happening for you.

The reason a segfault can happen is because finish() is a virtual function. Virtual functions work in C++ behind the scenes by basically using a virtual table of function pointers. A segfault can happen if something awry has gone wrong with those pointers.

I am 99.9% there is something wrong with your build/system.

Hey Ben... has this every happened to you?

**Comment by bentsherman** [comment]
Sorry I didn't get a notification about this issue for some reason... I haven't had this problem though. I agree with Josh that the segfault is probably related to virtual functions, maybe something is wrong with your library files for ACE? I'll run import expression matrix in a moment and see if I can replicate it.

**Comment by spficklin** [comment]
I don't seem to be having this issue anymore but I don't know what the problem was or the fix...
