### ISSUE TITLE
Main Window Redesign.

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#24]
I think we need to redesign the main window that ACE provides. It's not clear what it is when the program first loads.  It's just a white box.  A larger design meeting is probably necessary.

**Comment by bentsherman** [comment]
While I'm looking at this, the first idea that comes to my mind is to incorporate some UI elements into the main window that are currently separate:

- List the available data types to open, analytics to run, and OpenCL devices to select from, all in a side panel, to replace / supplement the menu options
- Keep the windows for viewing data objects and setting up analytics separate (it's useful to be able to view multiple data objects at once)
- Keep the console as an output log
- Possibly integrate the analytic progress bar into the main window since it always looks the same and is very small

**Comment by 4ctrl-alt-del** [comment]
I think the best thing we should do for this is sit down with a white board or something to draw on since this is GUI design. That being said I am all for making the GUI look nicer in the future. Right now I am personally more concerned with making KINC functional though.

**Comment by 4ctrl-alt-del** [comment]
Just to update this issue I have talked to all of you about the idea of converting the GUI interface for ACE to use qt quick. In this way the application can make their own UI however they like using QML in qt quick and then interface with ACE through qt objects made visible in QML.

**Comment by 4ctrl-alt-del** [comment]
This issue was resolved with smaller GUI enhancements that stephen requested and has been implemented.
