### ISSUE TITLE
--lmpi_cxx not needed

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#37]
When compiling ACE on Kamiak using MPI 3.0.0 I get an error with this library missing:  libmpi_cxx.  If I comment out that library all is good, so it's not needed.

**Comment by 4ctrl-alt-del** [comment]
While the libraries compile fine without mpi_cxx linking fails:

/home/alucinor/projects/ACE/src/example/../../build/libs/libacecore.so: undefined reference to `ompi_mpi_cxx_op_intercept'
/home/alucinor/projects/ACE/src/example/../../build/libs/libacecore.so: undefined reference to `MPI::Datatype::Free()'
/home/alucinor/projects/ACE/src/example/../../build/libs/libacecore.so: undefined reference to `MPI::Comm::Comm()'
/home/alucinor/projects/ACE/src/example/../../build/libs/libacecore.so: undefined reference to `MPI::Win::Free()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:390: aceex] Error 1
13:01:22: The process "/usr/bin/make" exited with code 2.

$ mpirun --version
mpirun (Open MPI) 2.0.2

So I don't see how I would be able to remove -lmpi_cxx because that breaks it for me. At which point I thought it might be the version so I upgraded to 3.0.1:

$ mpirun --version
mpirun (Open MPI) 3.0.1

And I still get the same linking errors:

/home/alucinor/projects/ACE/src/example/../../build/libs/libacecore.so: undefined reference to `ompi_mpi_cxx_op_intercept'
/home/alucinor/projects/ACE/src/example/../../build/libs/libacecore.so: undefined reference to `MPI::Datatype::Free()'
make[1]: Leaving directory '/home/alucinor/projects/ACE/build/example'
/home/alucinor/projects/ACE/src/example/../../build/libs/libacecore.so: undefined reference to `MPI::Comm::Comm()'
/home/alucinor/projects/ACE/src/example/../../build/libs/libacecore.so: undefined reference to `MPI::Win::Free()'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:390: aceex] Error 1
make: *** [Makefile:98: sub-example-make_first] Error 2
13:25:57: The process "/usr/bin/make" exited with code 2.

So at this point I cannot remove -lmpi_cxx because it breaks it and makes it so I cannot compile on my system. @bentsherman can you please chime in and let me know how this behaves on your system? I'm guessing there is something strange going on with Kamiak. I say this because it makes sense you would need to link mpi_cxx because that is the C++ library for MPI whereas linking mpi is just for the C library.

**Comment by 4ctrl-alt-del** [comment]
Since I have added a qmake option for including or not including mpi_cxx and it seems it is system specific on if it is needed or not I am going to close this.
