### ISSUE TITLE
Logger interface for analytics

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#40]
ACE should provide a logger, which would probably just be a thin wrapper over `QDebug`, so that analytics can log messages intelligently. So ACE console could just print the messages to the console, while ACE gui could print to the "fake" console or to a single-line buffer in the analytic window. That decision might be clearer after we redesign the ACE window to be more integrated.

Not a high priority by any means, but it might be useful to have a logger which is more integrated with ACE so that it doesn't clobber the percentage prints and things like that.

**Comment by 4ctrl-alt-del** [comment]
This has now become a top priority because of the most recent bug Stephen encountered. The bug did not show up until after running similarity for over 12 hours. Because of this I need to add very detailed debugging level logging ASAP to even have a chance of resolving this bug.

Not exactly what you were talking about but later on I can add regular logging messages. Right now I need to make the very low level debugging messages through.

**Comment by 4ctrl-alt-del** [comment]
Update.. because logging and debugging are almost identical I will be doing regular logging messages first, however you can hack it to be used for debugging on a temporary basis if needed. I doubt I will be able to get the debugging interface done before I leave but I think I can get basic logging in there.

Logging will work using a TCP server. The program will be listening on a certain port for new connections and anything connects will be given logging output. It is simple text to telnet should work to do that. Debugging will work the same way but much more detailed and complex.

**Comment by 4ctrl-alt-del** [comment]
Since the logging system is now complete this can be closed.
