### ISSUE TITLE
KINC hangs half-way through long run

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#62]
I'm running a large rice dataset on Kamiak.  I'm using 15 GPUs. Here's the submission script:

```
#!/bin/sh
#SBATCH --partition=ficklin
#SBATCH --account=ficklin
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=4
#SBATCH --gres=gpu:tesla:4
#SBATCH --time=96:00:00    
#SBATCH --job-name=KINC_rice_sim-control
#SBATCH --output=logs/02-KINC_rice_sim-control.log

module load gcc/6.1.0 MPI/openmpi/3.0.0 cuda/9.1.85 qt/5.10.1 ACE/dev KINC/3.2.1

kinc settings set logging on

srun --mpi=pmi2 -l kinc run similarity --input rice_PRJNA301554-GEM-log-no.control.emx --ccm rice_PRJNA301554-GEM-log-no.control.ccm --cmx rice_PRJNA301554-GEM-log-no.control.cmx --clusmethod gmm --corrmethod spearman -minexpr -inf --minsamp 30 --minclus 1 --maxclus 5 --crit ICL --preout TRUE --postout TRUE --mincorr 0.5 --maxcorr 1 --ksize 4096
```
It runs for about 12 hours then hangs. All GPU and CPU activities stop but the overall job does not fail and SLURM keeps it going.  It's just not doing anything.

**Comment by bentsherman** [comment]
So after talking to Josh I did some investigating of my own and I think I found the root cause. I was able to replicate the hang with this command:
```
kinc chunkrun 999 1000 similarity --input data/TCGA.emx
```

In other words I started Similarity towards the end of a GEM with over 70,000 genes. I think the issue was an infinite loop which was happening because a counter was overflowing into a negative number so it would never reach the stopping condition. I think I fixed this bug in the latest commit to KINC, but of course you guys should pull the changes and see for yourself. Going to keep running a few more tests.

**Comment by spficklin** [comment]
@bentsherman that's wonderful.  We'll pull and check.

**Comment by spficklin** [comment]
I can verity that this bug is now fixed in the development branch.  Just ran a 66339 x 141 GEM using GMMs and pre and post outlier removal using 15 GPUs. It completed in 17 hours!  I limited correlation values to no less than 0.5 and it generated a 2GB correlation file and a 12GB cluster file.
